In [1]:
%config IPCompleter.use_jedi = False 

In [12]:
import cv2
print('Open-CV version:{}'.format(cv2.__version__))

Open-CV version:4.5.2


In [13]:
#convert to grayscale
img = cv2.imread('test1.jpg',1)
#convert to grayscale
imgg = cv2.imread('test1.jpg',0)

In [14]:
#size of an array
print('RGB Shape:{}'.format(img.shape))

print('Grayscale Shape:{}'.format(imgg.shape))

RGB Shape:(533, 799, 3)
Grayscale Shape:(533, 799)


In [15]:
img.all

<function ndarray.all>

In [16]:
#array

print('RGB Array:{}'.format(img))
print('Grayscale Array:{}'.format(imgg))

RGB Array:[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 230 230]
  [232 230 230]
  [232 230 230]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 230 230]
  [232 230 230]
  [232 230 230]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 230 230]
  [232 230 230]
  [232 230 230]]

 ...

 [[142 166 194]
  [152 174 202]
  [151 172 200]
  ...
  [100 169 239]
  [ 99 168 238]
  [ 99 168 238]]

 [[150 158 181]
  [141 147 170]
  [148 154 177]
  ...
  [100 169 238]
  [100 169 238]
  [ 99 168 237]]

 [[149 158 185]
  [144 152 181]
  [146 154 183]
  ...
  [100 169 238]
  [ 99 168 237]
  [ 98 167 236]]]
Grayscale Array:[[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [172 180 178 ... 182 181 181]
 [164 153 160 ... 182 182 181]
 [165 160 162 ... 182 181 180]]


In [17]:
print(type(img))
print(type(imgg))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
#resize image
resized = cv2.resize(img, (int(img.shape[1]*2), int(img.shape[0]*2)))

In [23]:
#Display image
cv2.imshow('ImageRGB',resized)
# cv2.imshow('ImageGrayscale', imgg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
resized.shape

(1066, 1598, 3)

## FaceDetection in an image


In [ ]:
# %%writefile face_image.py

import cv2

# #Create a CascadeClassifier Object
# face_cascade = cv2.CascadeClassifier('./haarcascade/haarcascade_frontalface_default.xml')

# #Eeading the image as it is
# img = cv2.imread('test1.jpg')

# #Reading the image as gray scale image
# gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#load the photograph
pixels = cv2.imread('test1.jpg')
# load the pre-trained model
classifier = cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_default.xml')
#perform face detection
bboxes = classifier.detectMultiScale(pixels, 1.1, 8)
#print bounding box for each detect face
for box in bboxes:
    #extract
    #extract
    x,y, width, height = box
    x2, y2 = x+width, y+height
    #draw a rectangle over the pixels
    cv2.rectangle(pixels, (x,y), (x2, y2), (0,0,255),1)
#show the image
cv2.imshow('face detection', pixels)
#keep the window open until we press a key
cv2.waitKey(0)
#close the window
cv2.destroyAllWindows()

In [2]:
import cv2;

# Using the Haar Cascade from OpenCV
face_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_default.xml');

video = cv2.VideoCapture(0);

while True:
    check, frame = video.read();
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,
                                          scaleFactor=1.1, minNeighbors=5);
    for x,y,w,h in faces:
        gray = cv2.rectangle(gray, (x,y), (x+w,y+h), (0,255,0), 3);

    cv2.imshow('Face Detector',gray);

    key = cv2.waitKey(1);

    if key == ord('q'):
        break;

video.release();
cv2.destroyAllWindows();



In [7]:
!pwd

/Users/shovitraj/Github/OpenCV/FaceDetection


In [3]:
%%writefile face_webcam.py

import cv2;

face_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_default.xml');

video = cv2.VideoCapture(0);

while True:
    check, frame = video.read();
    faces = face_cascade.detectMultiScale(frame,
                                          scaleFactor=1.1, minNeighbors=5);
    for x,y,w,h in faces:
        frame = cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 3);

    cv2.imshow('Face Detector', frame);

    key = cv2.waitKey(1);

    if key == ord('q'):
        break;

video.release();
cv2.destroyAllWindows();


Writing face_webcam.py


In [2]:
# %%writefile eye_image.py

import cv2

pixels = cv2.imread('test1.jpg')
# load the pre-trained model
classifier = cv2.CascadeClassifier('./haarcascades/haarcascade_eye.xml')
#perform face detection
bboxes = classifier.detectMultiScale(pixels, 1.1, 8)
#print bounding box for each detect face
for box in bboxes:
    #extract
    #extract
    x,y, width, height = box
    x2, y2 = x+width, y+height
    #draw a rectangle over the pixels
    cv2.rectangle(pixels, (x,y), (x2, y2), (0,0,255),1)
#show the image
cv2.imshow('face detection', pixels)
#keep the window open until we press a key
cv2.waitKey(0)
#close the window
cv2.destroyAllWindows() 

In [ ]:
# %%writefile eye_image.py

import cv2

pixels = cv2.imread('test1.jpg')
# load the pre-trained model
classifier = cv2.CascadeClassifier('./haarcascades/haarcascade_smile.xml')
#perform face detection
bboxes = classifier.detectMultiScale(pixels, 1.1, 8)
#print bounding box for each detect face
for box in bboxes:
    #extract
    #extract
    x,y, width, height = box
    x2, y2 = x+width, y+height
    #draw a rectangle over the pixels
    cv2.rectangle(pixels, (x,y), (x2, y2), (0,0,255),1)
#show the image
cv2.imshow('face detection', pixels)
#keep the window open until we press a key
cv2.waitKey(0)
#close the window
cv2.destroyAllWindows() 